### ISSUE TITLE
smmap 6.0.0 was merged but never uploaded to conda-forge

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/smmap-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

smmap 6.0.0 was merged but never uploaded to conda-forge
https://anaconda.org/conda-forge/smmap

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

**Comment by ocefpaf** [comment]
Seems to be there: https://anaconda.org/conda-forge/smmap/files?version=6.0.0
